name: Secret Scanning
description: A custom GitHub Action
inputs:
  exclusions:
    description: 'Comma-separated list of files to exclude'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - run: cd $GITHUB_WORKSPACE &&
           git clone https://github.com/geekNero/testing-actions.git &&
           cd testing-actions &&
           mkdir actions
      shell: bash
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: python -m pip install --upgrade pip &&
           pip install -r testing-actions/requirements.txt
      shell: bash
    - run: cd $GITHUB_WORKSPACE && cd testing-actions && printenv
      shell: bash
    - uses: actions/checkout@v3
      with:
        path: 'testing-actions/actions/'