name: Secret Scanning
description: A custom GitHub Action
inputs:
  exclusions:
    description: 'Comma-separated list of files to exclude'
    required: false
    default: ''
runs:
  using: "composite"
    steps:
      - run: ls
        shell: bash